llm:
  api_base: ""
  api_key: ${TINKER_KEY}
  model_id: ${TINKER_MODEL}
  provider: tinker
mode: skills_only
proxy:
  host: 0.0.0.0
  port: 30000
rl:
  enabled: false
  model: ${TINKER_MODEL}
  tinker_api_key: ${TINKER_KEY}
scheduler:
  calendar:
    enabled: false
  enabled: false
skills:
  auto_evolve: false
  dir: ${METACLAW_ROOT}/memory_data/skills
  enabled: true
  retrieval_mode: template
  task_specific_top_k: 10
  top_k: 6
